apiVersion: v1
kind: Namespace
metadata:
  name: beer-marketplace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: beer-marketplace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: beer-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: beer-marketplace
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
