apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beer-marketplace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitlab.local:8090/root/beer-marketplace.git'
    targetRevision: HEAD
    path: helm/beer-marketplace
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: beer-marketplace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
